sudo: required
services:
  - docker

script:
  - docker build -t yijv/node .
  - docker images yijv/node

before_deploy:
  - docker login docker.io -u yijv -p Tangelo93

deploy:
  provider: script
  script: docker push yijv/node
  skip_cleanup: true
  on:
    branch: master