sudo: required
services:
  - docker

script:
  - docker build -t mannydesigns/node .
  - docker images mannydesigns/node
  - docker push mannydesigns/node

before_deploy:
  - docker login -u yijv -p Tangelo93

deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master